FROM allure-reporter-base:latest

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

RUN npm install -g http-server

COPY . .

RUN npm run build -- --prod --base-href="/allure-reporter/"

EXPOSE 4200

CMD ["http-server", "dist", "-p", "4200", "-a", "0.0.0.0"]
