FROM node:10-buster

# Install Python 3 and dependencies
RUN apt-get update && \
    apt-get install -y python3 python3-distutils python3-pip && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

RUN npm install -g serve