name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger deployment on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify the Node.js version to use

    # Install Python 3 (required by node-gyp)
    - name: Set up Python 3
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
        python --version  # Verify Python version

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Build project
    - name: Build project
      run: npm run build

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # The branch where the site will be deployed
        folder: build  # The folder that contains the built files (adjust if necessary)
        token: ${{ secrets.GITHUB_TOKEN }}  # Automatically available to actions
